export const FETCH_POSTS = "FETCH-POSTS";
export const ADD_POST = "ADD-POST";
export const DELETE_POST = "DELETE-POST";
export const CHANGE_PAGE = "CHANGE-PAGE";
export const CHANGE_PROFILE = "CHANGE-PROFILE";

export const FETCH_DIALOGS = "FETCH-DIALOGS";
export const FETCH_ONE_DIALOG = "FETCH-ONE-DIALOG";
export const CHANGE_DIALOG_LAST_MESSAGE = "CHANGE-DIALOG-LAST-MESSAGE";
export const GO_TO_DIALOG = "GO-TO-DIALOG";
export const CREATE_NEW_DIALOG = "CREATE-NEW-DIALOG";


export const ADD_MESSAGE = "ADD-MESSAGE";
export const FETCH_MESSAGES = "FETCH-MESSAGES";

export const FETCH_ONE_USER = "FETCH-ONE-USER";
export const FETCH_USERS = "FETCH-USERS";
export const UPDATE_PROFILE_DATA = "UPDATE_PROFILE_DATA";
export const CLEAN_ALL_USERS = "CLEAN-ALL-USERS";
export const FETCH_CURRENT_LOGIN = "FETCH-CURRENT-LOGIN";

export const REGISTRATION = "REGISTRATION";
export const LOGIN = "LOGIN";
export const LOG_OUT = "LOG-OUT";
export const SET_LOGIN = "SET-LOGIN";
export const SET_LOADING = "SET-LOADING";

export const FETCH_FRIENDS = "FETCH-FRIENDS";
export const FETCH_ONE_FRIEND = "FETCH-ONE-FRIEND";
export const ADD_FRIEND = "ADD-FRIEND";
export const DELETE_FRIEND = "DELETE-FRIEND";

export const FETCH_FRIEND_REQUESTS = "FETCH-FRIEND-REQUESTS";
export const FETCH_ONE_REQUEST = "FETCH-ONE-REQUEST";
export const ACCEPT_FRIEND_REQUEST = "SEND-FRIEND-REQUEST";
export const REJECT_FRIEND_REQUEST = "REJECT-FRIEND-REQUEST";
export const SEND_FRIEND_REQUEST = "SEND-FRIEND-REQUEST";
export const DELETE_FRIEND_REQUEST = "DELETE-FRIEND-REQUEST";

export const API_ERROR = "API-ERROR";