export const FETCH_POSTS = "FETCH-POSTS";
export const ADD_POST = "ADD-POST";
export const DELETE_POST = "DELETE-POST";
export const CHANGE_PAGE = "CHANGE-PAGE";
export const CHANGE_PROFILE = "CHANGE-PROFILE";

export const FETCH_DIALOGS = "FETCH-DIALOGS";
export const FETCH_ONE_DIALOG = "FETCH-ONE-DIALOG";
export const CHANGE_DIALOG_LAST_MESSAGE = "CHANGE-DIALOG-LAST-MESSAGE";


export const ADD_MESSAGE = "ADD-MESSAGE";
export const FETCH_MESSAGES = "FETCH-MESSAGES";

export const FETCH_ONE_USER = "FETCH-ONE-USER";
export const FETCH_ONE_USER_POST = "FETCH-ONE-USER-POST";
export const FETCH_USERS = "FETCH-USERS";
export const CLEAN_ALL_USERS = "CLEAN-ALL-USERS";
export const FETCH_CURRENT_LOGIN = "FETCH-CURRENT-LOGIN";




